name: learn-github-actions
run-name: ${{ github.actor }} is learning github actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v3
      # This step references the directory that contains the action.
      - uses: ./.github/actions/hello-world-action  
      - run: npm install -g bats
      - run: bats -v
jobs:
  my_first_job:
    steps:
      - name: My first step
        uses: actions/setup-node@v3
jobs:
  my_second_job:
    steps:
      - name: My second step
        uses: docker://alpine:3.8              